### ISSUE TITLE
Climate devices with setpoint_shift

### ISSUE THREAD

**Issue by marvin-w** [XKNX/xknx#183]
While testing #175 @Julius2342 encountered below error which needs to be analysed and properly fixed.

```
2019-02-19 09:51:47 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/julius/home-assistant/homeassistant/helpers/service.py", line 291, in _handle_service_platform_call
    await func(entity, data)
  File "/home/julius/home-assistant/homeassistant/components/climate/__init__.py", line 564, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/home/julius/home-assistant/homeassistant/components/knx/climate.py", line 238, in async_set_temperature
    await self.device.set_target_temperature(temperature)
  File "/home/julius/xknx/xknx/devices/climate.py", line 180, in set_target_temperature
    await self.set_target_temperature_setpoint_shift(target_temperature)
  File "/home/julius/xknx/xknx/devices/climate.py", line 191, in set_target_temperature_setpoint_shift
    raise DeviceIllegalValue("setpoint_shift_max exceeded", setpoint_shift)
xknx.exceptions.exception.DeviceIllegalValue: <DeviceIllegalValue description="setpoint_shift_max exceeded" value="68" />

```

**Comment by farmio** [comment]
We are comparing setpoint_shift value (K/setpoint_shift_step) with setpoint_shift_max (K).
Either we multiply setpoint_shift by setpoint_shift_step before comparison
```python
async def set_target_temperature_setpoint_shift(self, target_temperature):
    """Set target temperature via setpoint_shift group address."""
    temperature_delta = target_temperature-self.target_temperature.value
    setpoint_shift_delta = int(temperature_delta/self.setpoint_shift_step)
    setpoint_shift = self.setpoint_shift.value + setpoint_shift_delta

    if (setpoint_shift * self.setpoint_shift_step) > self.setpoint_shift_max:
        raise DeviceIllegalValue(
            "setpoint_shift_max exceeded", setpoint_shift)
    elif (setpoint_shift * self.setpoint_shift_step) < self.setpoint_shift_min:
        raise DeviceIllegalValue(
            "setpoint_shift_min exceeded", setpoint_shift)

    await self.setpoint_shift.set(setpoint_shift)
```

or we save `setpoint_shift_max` and min directly like
```python
self.setpoint_shift_max = setpoint_shift_max / setpoint_shift_step
self.setpoint_shift_min = setpoint_shift_min / setpoint_shift_step
```

If self.setpoint_shift_min or max was exceeded: target_temperature should be set back to previous value to ensure synced states.
