### ISSUE TITLE
ValueError: [448,256] is not a valid APCICommand

### ISSUE THREAD

**Issue by elupus** [XKNX/xknx#226]
**Description of problem:**
Exception during processing of messages, likely while ETS is communicating with new Secure IP Interface.

- [ ] using xknx standalone
- [X] using Home-Assistant knx plugin

**Version information:**
- xknx / Home-Assistant release with the issue: 0.98
- last working xknx / Home-Assistant release (if known): None

**KNX installation:**

ETS 5.7.2

**Problem-relevant `xknx.yaml` or `configuration.yaml` entries (fill out even if it seems unimportant):**

**Traceback (if applicable):**
```
Aug 19 19:09:24 hass hass[32967]: Traceback (most recent call last):
Aug 19 19:09:24 hass hass[32967]:   File "/usr/lib/python3.6/asyncio/events.py", line 127, in _run
Aug 19 19:09:24 hass hass[32967]:     self._callback(*self._args)
Aug 19 19:09:24 hass hass[32967]:   File "/usr/lib/python3.6/asyncio/selector_events.py", line 1078, in _read_ready
Aug 19 19:09:24 hass hass[32967]:     self._protocol.datagram_received(data, addr)
Aug 19 19:09:24 hass hass[32967]:   File "/home/homeassistant/env/lib/python3.6/site-packages/xknx/io/udp_client.py", line 55, in datagram_received
Aug 19 19:09:24 hass hass[32967]:     self.data_received_callback(data)
Aug 19 19:09:24 hass hass[32967]:   File "/home/homeassistant/env/lib/python3.6/site-packages/xknx/io/udp_client.py", line 87, in data_received_callback
Aug 19 19:09:24 hass hass[32967]:     knxipframe.from_knx(raw)
Aug 19 19:09:24 hass hass[32967]:   File "/home/homeassistant/env/lib/python3.6/site-packages/xknx/knxip/knxip.py", line 78, in from_knx
Aug 19 19:09:24 hass hass[32967]:     pos += self.body.from_knx(data[pos:])
Aug 19 19:09:24 hass hass[32967]:   File "/home/homeassistant/env/lib/python3.6/site-packages/xknx/knxip/tunnelling_request.py", line 48, in from_knx
Aug 19 19:09:24 hass hass[32967]:     pos += self.cemi.from_knx(raw[pos:])
Aug 19 19:09:24 hass hass[32967]:   File "/home/homeassistant/env/lib/python3.6/site-packages/xknx/knxip/cemi_frame.py", line 113, in from_knx
Aug 19 19:09:24 hass hass[32967]:     return self.from_knx_data_link_layer(raw)
Aug 19 19:09:24 hass hass[32967]:   File "/home/homeassistant/env/lib/python3.6/site-packages/xknx/knxip/cemi_frame.py", line 143, in from_knx_data_link_layer
Aug 19 19:09:24 hass hass[32967]:     self.cmd = APCICommand(tpci_apci & 0xFFC0)
Aug 19 19:09:24 hass hass[32967]:   File "/usr/lib/python3.6/enum.py", line 291, in __call__
Aug 19 19:09:24 hass hass[32967]:     return cls.__new__(cls, value)
Aug 19 19:09:24 hass hass[32967]:   File "/usr/lib/python3.6/enum.py", line 533, in __new__
Aug 19 19:09:24 hass hass[32967]:     return cls._missing_(value)
Aug 19 19:09:24 hass hass[32967]:   File "/usr/lib/python3.6/enum.py", line 546, in _missing_
Aug 19 19:09:24 hass hass[32967]:     raise ValueError("%r is not a valid %s" % (value, cls.__name__))
Aug 19 19:09:24 hass hass[32967]: ValueError: 448 is not a valid APCICommand
```

```
Aug 22 08:15:49 hass hass[35975]: ValueError: 256 is not a valid APCICommand
Aug 22 08:15:49 hass hass[35975]:     raise ValueError("%r is not a valid %s" % (value, cls.__name__))
Aug 22 08:15:49 hass hass[35975]:   File "/usr/lib/python3.6/enum.py", line 546, in _missing_
Aug 22 08:15:49 hass hass[35975]:     return cls._missing_(value)
Aug 22 08:15:49 hass hass[35975]:   File "/usr/lib/python3.6/enum.py", line 533, in __new__
Aug 22 08:15:49 hass hass[35975]:     return cls.__new__(cls, value)
Aug 22 08:15:49 hass hass[35975]:   File "/usr/lib/python3.6/enum.py", line 291, in __call__
Aug 22 08:15:49 hass hass[35975]:     self.cmd = APCICommand(tpci_apci & 0xFFC0)
Aug 22 08:18:24 hass hass[35975]:   File "/usr/lib/python3.6/asyncio/base_events.py", line 1426, in _run_once
Aug 22 08:18:24 hass hass[35975]:     self._run_once()
Aug 22 08:18:24 hass hass[35975]:   File "/usr/lib/python3.6/asyncio/base_events.py", line 421, in run_forever
Aug 22 08:18:24 hass hass[35975]:     self.run_forever()
Aug 22 08:18:24 hass hass[35975]:   File "/usr/lib/python3.6/asyncio/base_events.py", line 454, in run_until_complete
Aug 22 08:18:24 hass hass[35975]:     return loop.run_until_complete(main)
Aug 22 08:18:24 hass hass[35975]:   File "/home/homeassistant/env/lib/python3.6/site-packages/homeassistant/util/async_.py", line 37, in asyncio_run
Aug 22 08:18:24 hass hass[35975]:     exit_code = asyncio_run(setup_and_run_hass(config_dir, args))
Aug 22 08:18:24 hass hass[35975]:   File "/home/homeassistant/env/lib/python3.6/site-packages/homeassistant/__main__.py", line 419, in main
Aug 22 08:18:24 hass hass[35975]:     sys.exit(main())
Aug 22 08:18:24 hass hass[35975]:   File "/home/homeassistant/env/bin/hass", line 10, in <module>

```

**Comment by elupus** [comment]
I have the docs, but also found the list of APCI commands here:
https://github.com/knxd/PyKNyX/blob/e7568fecf28953dc79aa7185b8514de0a7983422/pyknyx/stack/layer7/apci.py

So i likely hit a ADC_RES.

**Comment by elupus** [comment]
This seem to crash home assistant since this is not handled by the background task.

**Comment by Julius2342** [comment]
Hi @elupus,

there are two problems. The first one is that this APCICommand should be handled correctly.

The second one is that the Exception is not "hashable". The Hash function was removed from @farmio with commit 9cfbc5f25d88c65278e64dc3dd40a07c7673f6a5 . Now we know again why it is needed :-) ( #228 )

**Comment by farmio** [comment]
The specs call this "A_ADC_Response-PDU" that shall only be implementd in "point-to-point connection-orioented" communication modes described in 3/3/7 Application Layer §3.5.3

From knx specs 3/3/7 Application Layer §2 APDU I'd read we shall ignore unsupported commands:

> The complete PDU for each service primitive is shown in the description of every service. Not defined and not supported Application Layer services shall be ignored by the Application Layer.

Shall we change
https://github.com/XKNX/xknx/blob/4b71c28db4cde694695da3dfad0072dd5383717f/xknx/knxip/cemi_frame.py#L143
to something like
```python
try: 
    self.cmd = APCICommand(tpci_apci & 0xFFC0)
except ValueError:
    raise CouldNotParseKNXIP("APCI not supported")
```
or even just `self.xknx.knx_logger.debug("APCI not supported: %s", (tpci_apci & 0xFFC0))`?

**Comment by elupus** [comment]
Yea that should absolutely be done to avoid the ValueError leaking out. Isn't there a point in supporting to parse all known values thou? We can ignore them even if we parse them.
