### ISSUE TITLE
Error thrown when Reading DPT 9.004

### ISSUE THREAD

**Issue by ssoerensen** [XKNX/xknx#69]
I have setup a sensor in home assitant. and when ever the lux value updates a error is thrown, however the value is update.

ETS Group
 | 3/2/0 | Driveway-SEN-LUX |   | No | No | lux (Lux) | 2 bytes |   |  

Error message:
```
2017-09-25 11:58:42 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.drivewaysenlux, old_state=<state sensor.drivewaysenlux=595.84; unit_of_measurement=lx, friendly_name=Driveway Measured Lux @ 2017-09-25T13:58:31.623374+02:00>, new_state=<state sensor.drivewaysenlux=544.0; unit_of_measurement=lx, friendly_name=Driveway Measured Lux @ 2017-09-25T13:58:42.614233+02:00>>
2017-09-25 11:58:42 ERROR (MainThread) [xknx.log] Exception while processing telegram: unsupported operand type(s) for &: 'tuple' and 'int'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/xknx/core/telegram_queue.py", line 99, in process_telegram
    yield from self.process_telegram_incoming(telegram)
  File "/usr/local/lib/python3.6/site-packages/xknx/core/telegram_queue.py", line 130, in process_telegram_incoming
    yield from device.process(telegram)
  File "/usr/local/lib/python3.6/site-packages/xknx/devices/binary_sensor.py", line 133, in process
    binary_value = telegram.payload.value & bit_masq != 0
TypeError: unsupported operand type(s) for &: 'tuple' and 'int'

```

**Comment by Julius2342** [comment]
You have to define this device as a "sensor" not a "binarysensor". Then it should work.

**Comment by ssoerensen** [comment]
It is defined as a sensor
`sensor:
  - platform: knx
    name: Driveway-SEN-LUX
    type: illuminance
    icon: mdi:theme-light-dark
    address: '3/2/0' # Lux over 300 turn of lights
`

**Comment by Julius2342** [comment]
The stacktrace just happens somewhere within binary_sensor. So it looks like you have defined a binary_sensor with a group_address which is receiving a two-byte KNX telegram.

**Comment by ssoerensen** [comment]
Oh fuck. i'm just going to close this one again.. i have same group address referenced as a sensor as well *FACE PALM*!

**Comment by Julius2342** [comment]
happens :-)

But we should make the error message more readable ....
